### ISSUE TITLE
Nginx suggested config is not in the install page

### ISSUE THREAD

**Issue by nestor-alonso** [webpy/webpy.github.com#131]
Hi all:

In the install page, there are 3 different setups: with the dev server, with Apache and with Lighttpd. The information related to Nginx configuration is in the Cookbook:

http://webpy.org/cookbook/mod_wsgi-nginx
http://webpy.org/cookbook/fastcgi-nginx

Maybe we should validate that info and merge it  into the Install page, or at least include some reference to Nginx.

**Comment by iredmail** [comment]
Fixed. Thanks @nestor-alonso :)
