### ISSUE TITLE
Pictures... any examples of all this cool stuff

### ISSUE THREAD

**Issue by datatalking** [webpy/webpy.github.com#133]
It's great to hear of a python based web platform, but unless you are a seasoned developer or can translate what code generates... the rest of us have little to no idea what it makes.

Can you post photos of the webpage it makes, examples of what it looks like? Screenshots of a web.py project that showcases how its easier or better to use vs what Django might be used in error to create.

**Comment by datatalking** [comment]
So that’s a no in the “documentation for people who are not smarty pants devils geniuses like you”?

**Comment by iredmail** [comment]
People didn’t share their websites, so we don’t have something to show on website. :(

**Comment by cclauss** [comment]
https://openlibrary.org for example.

**Comment by bpluly** [comment]
Web.py is a minimalist framework for web applications. Apart from
templating, it doesn't concern itself with the front end or browser, it's a
back end framework.

Insofar as its coolness, that's really in the straightforward way it helps
you build web applications in a pythonesque way, ie you can use the
strengths of the language to deliver complex web apps relatively simply.

More and better samples are needed but they would be pretty invisible in
terms of 'pictures'.

**Comment by Allyn69** [comment]
![Image](https://i.imgur.com/PfA7Hxd.jpg)
