### ISSUE TITLE
Update "Who uses web.py" section on homepage

### ISSUE THREAD

**Issue by benhoyt** [webpy/webpy.github.com#47]
I just proposed an update to the Oyster.com entry because of I have knowledge of that. However, several of the other items are out of date (I believe).

Frinki.com doesn't lead anywhere, except some spammy-looking redirect pages.

Some of the other items feel out of date to me (they haven't been updated in a long time). And I wonder if we could add other highish-profile websites by now?

**Comment by kvfi** [comment]
I had the same observation. By looking at the date of submission, looks like not much has been done: 6 dead links.
