### ISSUE TITLE
Update cookbook/streaming_large_files: Remove chunked for WSGI deployed applications

### ISSUE THREAD

**Issue by timtebeek** [webpy/webpy.github.com#58]
Streaming a large file using chunked worked fine when ran directly through webpy's built-in server, but when deployed in Apache using mod_wsgi it failed with an IOError. I found this similar issue report and can confirm it works without setting the chunked transfer header:
http://stackoverflow.com/questions/11866333/ioerror-when-trying-to-serve-file

Could you update the documentation to either remove the mention of chunked, or specify in which exclusive cases to use the chunked header?

**Comment by iredmail** [comment]
Fixed. https://github.com/webpy/webpy.github.com/commit/12fae0bf693cc28e64b6d5f4a1ae3e243491420e

**Comment by anandology** [comment]
> (Note: applications and middleware must not apply any kind of Transfer-Encoding to their output, such as chunking or gzipping; as "hop-by-hop" operations, these encodings are the province of the actual web server/gateway. See Other HTTP Features below, for more details.)
-- PEP 333 -- Python Web Server Gateway Interface v1.0

I think it is not correct to ask the application to set the `Transfer-Encoding` header

**Comment by iredmail** [comment]
@anandology It's clearly mentioned that it's used only when you run web.py builtin web server. And not required if using Apache/Nginx as web server.
