### ISSUE TITLE
Error when doing Django style multiple apps with web.py

### ISSUE THREAD

**Issue by siongui** [webpy/webpy.github.com#59]
When following the tutorial [Django style multiple apps with web.py](http://webpy.org/multiple_apps), I alway get the following error:

``` bash
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    delegate.run(mapping)
  File "/home/siongui/dev/test/delegate.py", line 31, in run
    web.run(handler, {})
AttributeError: 'module' object has no attribute 'run'
```

My scripts are the same as those in the tutorial. Could you please help fix this?

**Comment by iredmail** [comment]
Try sub-application setup instead:
http://webpy.org/cookbook/subapp
