### ISSUE TITLE
solely nginx compatible web.py

### ISSUE THREAD

**Issue by umrashrf** [webpy/webpy.github.com#76]
I just deployed an app on an Ubuntu 12.04 machine following this guide http://webpy.org/cookbook/fastcgi-nginx

Although the app works but it seems the guide is very old as flup link is not working. It also looks like spawn-fcgi is not in active development and soon will be deprecated. I was wondering if web.py can run on bare nginx?

I don't like to use spawn-fcgi and flup just don't make sense. Why not add flup and spawn-fcgi into web.py itself?

**Comment by iredmail** [comment]
You can use uwsgi, gunicorn or other wsgi server to run webpy application, then configure Nginx to proxy the requests to wsgi server.
