### ISSUE TITLE
cookie_path missing from WSGI documentation

### ISSUE THREAD

**Issue by maxwellworthington** [webpy/webpy.github.com#84]
Hello,

The sample code for sessions with WSGI should read:

app = web.application(urls, globals())

curdir = os.path.dirname(**file**)
web.config.session_parameters['cookie_path'] = '/'
session = web.session.Session(app, web.session.DiskStore(os.path.join(curdir,'sessions')),)

application = app.wsgifunc()

I found this solution on stackoverflow:
http://stackoverflow.com/questions/22076781/web-py-sessions-renew-every-reload-under-apache-cgi-wsgi

Thanks,
Mark

**Comment by iredmail** [comment]
`cookie_path` is mentioned in doc for `session` module:
http://webpy.org/cookbook/sessions
